name: Release


on:
  push:
    branches:
      - ignore 
#      - master
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-crates-io:
    name: Release crates.io
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: cargo publish
        run: cargo publish

